### ISSUE TITLE
:v

### ISSUE THREAD

**Issue by DaviPatrick** [dbm-add-ons/DBM-Add-Ons#2]
make a pullrequest to dbm-network, and pls send those mods, extensions and events :)
will help a lot of users

**Comment by Thaliruth** [comment]
These are Addons, it is not comparable to the DBM Mods. These add-ons are more for experienced DBM users

**Comment by ACertainCoder** [comment]
The problem is not only that the DBM Add-Ons are much more complicated to use, some of mods by the DBM Network aren't even compatible with our Dependency which would cause some bots to crash completely.
